# Generated by Django 6.0.4 on 2026-04-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_alter_budget_amount_alter_budget_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='currency',
            field=models.CharField(choices=[('₹', 'Indian Rupee'), ('$', 'US Dollar'), ('€', 'Euro'), ('£', 'British Pound')], default='₹', max_length=10),
        ),
    ]
