# Generated by Django 6.0.4 on 2026-04-22 18:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0004_alter_expenses_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='month',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
