# Generated by Django 6.0.4 on 2026-04-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0006_alter_budget_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='note',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
