# Generated by Django 6.0.4 on 2026-06-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0008_alter_budget_month_alter_income_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='currency',
            field=models.CharField(choices=[('₹', 'Indian Rupee'), ('$', 'US Dollar'), ('SGD', 'Singapore Dollar'), ('AED', 'UAE Dirham')], default='₹', max_length=10),
        ),
    ]
