# Generated by Django 6.0.4 on 2026-06-01 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0009_alter_profile_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='note',
        ),
    ]
